# Generated by Django 5.2.5 on 2025-08-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', models.ImageField(blank=True, upload_to='fotos/noticias/')),
                ('pruebas_en_pdf', models.FileField(blank=True, upload_to='raw/noticias')),
                ('video', models.FileField(blank=True, upload_to='videos/noticias')),
            ],
        ),
    ]
